name: CDN CI
on:
  push:
    branches: [ main ]
env:
  MANDY_ENV: "production"
  MANDY_URL: "https://github.com/alyxshang/mandy/releases/download/v.0.1.0/mandy-linux-v.0.1.0"
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build the CDN."
        run: |
          bash build.sh

      - name: "Verify the build."
        run: tree

      - name: "Deploy the built site."
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: cdn
