name: CDN CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.43.3
        
      - name: "Copy assets to one folder."
        run: bash build.sh

      - name: "Deploy."
        uses: garygrossgarten/github-action-scp@release
        with:
         local: cdn
         remote: /var/www/html/cdn.alyxshang.boo
         host: ${{ secrets.FTP_IP }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FT_PWD }}
         atomicPut: true
         recrusive: true
