name: CDN CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.43.3
        
      - name: "Copy assets to one folder."
        run: bash build.sh

      - name: "Deploy."
        uses: SamKirkland/FTP-Deploy-Action@3.2.0
        with:
          server: ${{ secrets.FTP_IP }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PWD }}
          server-dir: html/cdn.alyxshang.boo/cdn
          local-dir: ./cdn
